development: &default
  adapter: postgresql
  database: tdpos_dev
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 2
  timeout: 5000

test:
  <<: *default
  database: tdpos_test

production:
  <<: *default
  database: tdpos_production
  encoding: utf8
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>